name: Install Tools & Dependencies
description: Installs Node.js & package dependencies

runs:
  using: composite
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20
        
    - name: Cache Node dependencies
      id: cache-dependencies
      uses: actions/cache@v4
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}-clear
        
    - name: Install Node dependencies
      if: steps.cache-dependencies.outputs.cache-hit != 'true'
      run: yarn install --immutable
      shell: bash
