name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Automatically cancel in-progress actions on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  code-check:
    name: Check for code issues with Astro check, TSC and ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Tools & Dependencies
        uses: ./.github/actions/install

      - name: Run Check
        run: |
          pnpm astro check
          pnpm tsc --noEmit
          pnpm lint:eslint
  # a11y-check:
  #   name: Check for a11y issues with Pa11y
  #   runs-on: ubuntu-latest
  #   needs: code-check
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Install Tools & Dependencies
  #       uses: ./.github/actions/install

  #     - name: Run Check
  #       run: yarn lint:a11y
