name: Deploy

on:
  push:
    branches: [main]
  schedule:
    - cron: "2 0 1 1 *" # rebuild and deploy every 1st january for footer year 😎

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Install Tools & Dependencies
        uses: ./.github/actions/install
        
      - name: Build site
        run: yarn build --silent
        
      - name: Deploy
        env:
          host: ${{ secrets.DEPLOY_HOST }}
          host_port: ${{ secrets.DEPLOY_PORT || 22 }}
          path: ${{ secrets.DEPLOY_PATH }}
        run: |
          echo "${{ secrets.DEPLOY_KEY }}" > deploy_key
          chmod 600 ./deploy_key
          cd dist
          rsync -chaqz --delete \
            -e 'ssh -p ${{ env.host_port }} -i ../deploy_key -o StrictHostKeyChecking=no' \
            ./ ${{ env.host }}:${{ env.path }}
